### ISSUE TITLE
App Icon not used in App store

### ISSUE THREAD

**Issue by krisgesling** [nextcloud/appstore#1262]
## Details
I'm curious why most apps shown in the App store display the default cog icon instead of the icon defined in their navigation metadata?

Eg here is the Hub bundle list where "Mail" and "Talk" are cogs:
![image](https://github.com/nextcloud/appstore/assets/2058458/c0896a38-0099-402c-929c-83605328c3f6)

This also gets shown in a list of App search results. So could help users to more easily differentiate the returned list of apps they're looking at.

For apps like Calendar that show a custom icon, where is this defined beyond the Navigation block in `info.xml`?

**Comment by bigcat88** [comment]
This is the wrong place to ask about this, since as far as I understand, this is a screenshot from the Nextcloud interface.
Most likely it’s worth asking in the Server repository where this code itself is located that displays the icons.

_This repository is only for **apps.nextcloud.com** website issues._

**Comment by krisgesling** [comment]
Thanks for the pointer @bigcat88 - have logged a feature request in the server repo.
https://github.com/nextcloud/server/issues/42645
