### ISSUE TITLE
Support zip archives

### ISSUE THREAD

**Issue by oparoz** [nextcloud/appstore#174]
It would be nice to support zip archives

**Comment by BernhardPosselt** [comment]
Unsure for a couple of reasons:

* keeping it to a single type of archive will make it much easier for people to implement the api. This also applies to package maintainers
* the generated ocdev makefile builds a tar.gz archive
* security checks are quite extensive, we need to duplicate a lot of test files and tests
* implementation will take some time because of the above mentioned points. Adding zip support later on will therefore likely break the api
* on windows it may prevent people from extracting the archive before uploading it over ftp. This is a benefit IMHO because ftp is weird and sometimes corrupts files

**Comment by BernhardPosselt** [comment]
Basically looks to me that the lack of zip support is a feature :)

Especially on php people can depend on one extension less which can be crucial ;)

**Comment by oparoz** [comment]
Most of your points are valid :)
And since the target user is a developer, I think that person can manage to create a tar.gz archive
