### ISSUE TITLE
App Licenses

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#28]
All apps need to be licensed at least under the AGPL if they are used by any users. Since you can have more than one license in our database model, should we validate, that at least the agpl is set as license?

So if you want to license your app under the MIT license you'd put the following into your info.xml:

``` xml
<licence>agpl</licence>
<licence>mit</licence>
```

As for the available licenses: I'd keep it small and only support the latest MIT, AGPL, MPL and Apache License.

**Comment by LukasReschke** [comment]
Fixed now by only allowing AGPL.

**Comment by jospoortvliet** [comment]
@schiessle what licenses would you think we should allow? I'd say at least, indeed, MIT, AGPL, MPL and Apache License, correct?

**Comment by bud-mo** [comment]
I will follow this discussion :smile:

**Comment by schiessle** [comment]
> what licenses would you think we should allow? I'd say at least, indeed, MIT, AGPL, MPL and Apache License, correct?

Only MPL 2.0 is compatible with the GNU AGPLv3. So if we add MPL to the list, we need to specify the version.

I would also suggest to keep the list short, otherwise it will just result in more confusion:

My personal List would be:

* GNU AGPLv3  or later (strong protection of the users rights)
* Mozilla Public license 2.0 (weak protection of the users rights)
* Apache License (no protection but at least it protected against patent threats to some extend)

For popularity reasons it might make sense to add the MIT License, although I believe people who prefer non-protecting licenses should chose the Apache License because of the patent grant. 

Default should be GNU AGPLv3 or later.

**Comment by jospoortvliet** [comment]
Sounds good to me. @bud-mo works for you, too?

How/where can this be implemented?!? Would be nice so @bud-mo can provide their app in the app store!

**Comment by BernhardPosselt** [comment]
Just add 2 lines like this https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/api/v1/release/info.xsd#L325 directly below with the values of **apache** and **mpl**. That's all.

**Comment by BernhardPosselt** [comment]
apache and mpl are now available once deployed
