### ISSUE TITLE
Move app scaffolding to app store

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/appstore#316]
There's always a ton of bikeshedding of what should go into ncdev and how and in which language it should be written.

Most of ncdevs features are actually very simple aliases for bash commands that can very well be moved into a bash alias, namely: 

* **server**: php -S localhost:8080
* **setup**: git clone https://github.com/nextcloud/server.git --recursive

The remaining features are:
* **devup**: very unreliable on my server
* **startapp**: important for app generation
* **appstore**: simpler curl

The only important feature I see here is app scaffolding. To prevent the bikeshed and make it easy for users to get started (no libs, no runtimes required) I want to move the startapp command to the app store.

It should work similar to Bootstrap http://getbootstrap.com/customize/ : You enter all the required details into a form, we generate an archive and let you download it.

To prevent DDoS attacks such as filling up our memory or disk space, users need to be logged in and only one archive per user is generated at once (hash over username should be used as tmp file name). This also means that the form can not be submitted in parallel which shouldn't be an issue.

**Comment by BernhardPosselt** [comment]
cc @janibonnevier @LukasReschke

**Comment by ccoenen** [comment]
From my point of view (not a python developer), having an extra interpreter, packet manager and toolset in a language I am not too familiar with, is a bad idea. I might be biased because I wanted to get into App development recently, got to the tutorials mentioning [ncdev](https://github.com/nextcloud/ncdev/issues/10) and got stuck even before I could get started. If you're new to this and all the documentation says "it should be this way" you'll search for a good while before giving up and reporting a bug.

Personally, I like the approach of an online generator. Then again, a command line tool could to so much more. It could - one day - also scan for deprecated or internal API use, or help you upgrade, or check for the Nextcloud codestyle and so on.

**Comment by LukasReschke** [comment]
> It could - one day - also scan for deprecated or internal API use, or help you upgrade, or check for the Nextcloud codestyle and so on.

Try `php ./occ app:check-code $APPNAME` :-)

**Comment by ccoenen** [comment]
In that case, either move _development related_ stuff out into `ncdev`, or kill off `ncdev` as suggested in this ticket and move everything in with `occ`. But now that you mention it, occ + ncdev are a weird mixture of both with no clear distinction.

**Comment by BernhardPosselt** [comment]
@ccoenen the distinction is that occ is used for Nextcloud administration. The app checker just happens to built into Nextcloud because they validate the packages before install ;)

Apart from that things are still chaotic and dev docs are absolutely outdated. Will take some time to get everything back to being ordered ;)

**Comment by janibonnevier** [comment]
Until the docs are sorted out it might be a good idea to say somewhere that they are outdated. Some months ago I spent way too many hours being confused.

**Comment by BernhardPosselt** [comment]
@janibonnevier feel free to do so :)
