### ISSUE TITLE
Loading forever

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/appstore#344]
![image](https://cloud.githubusercontent.com/assets/3178412/19383883/770704fa-91fe-11e6-81f8-353c60aa6358.png)

`Error	core	Could not get application: Client error response [url] https://apps.nextcloud.com/api/v0/content/data/166055?version=9x0x53x0 [status code] 404 [reason phrase] Not Found`

This happens when navigating the categories from a NC9 snappy core NCBox instance.
They never load (obviously).

Meta: https://help.nextcloud.com/t/new-app-store-nextcloud-9-10-testers-wanted/4160

**Comment by BernhardPosselt** [comment]
Yep, experienced that too but that's a bug in the server repo. As for the 404: Looks like its trying to find updates for an installed app that was not uploaded to the new store yet

**Comment by jasonbayton** [comment]
That is unfortunately the only relevant log entry (replicated several times for different version numbers) I didn't experience this with "stock" app store and there are no additional apps beyond Files, Activity and Gallery

**Comment by BernhardPosselt** [comment]
@jasonbayton can you get the spinner to disappear if you click around in the ui?

**Comment by jasonbayton** [comment]
Not unless I change category. Some categories load quickly, most spin forever.

**Comment by BernhardPosselt** [comment]
Right, but you get them to show up right?

**Comment by jasonbayton** [comment]
I'm not sure what you mean, so screenshots: 

![Uploading Apps   Nextcloud.png…]()

![apps nextcloud2](https://cloud.githubusercontent.com/assets/3178412/19386349/9093df80-920b-11e6-9e66-34e497e6f0db.png)

![apps nextcloud3](https://cloud.githubusercontent.com/assets/3178412/19386348/90930380-920b-11e6-8815-7cdf45ec5646.png)

**Comment by BernhardPosselt** [comment]
What I mean is: 
* You click on category Office & Text
* It shows an endless spinner
* You click on category Files
* It shows an app like posted above
* You jump between the two categories until there is no Spinner for Office & Text

**Comment by jasonbayton** [comment]
Ok, in which case no - no matter how much I click the spinner hasn't vanished. It loads forever (so far up to 20 mins)

**Comment by BernhardPosselt** [comment]
Ok, debugged it: the issue is the same for 
* authentication & authorization
* social & communication
* office & text

The reason is that no requests are made from the web interface if you click on that category. It seems that they dont use category ids but munch them in some sort of string format that can't deal with the ampersand.

Solution is probably to strip the **&** in the API and replace it with **and** since I doubt that people will put much work into fixing this :)

My next guess is that categories also fail if they contain whitespace. In that case we must strip the rest and only deliver the first word as category
