### ISSUE TITLE
Rename Authentication & authorization

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/appstore#375]
**Authentication & authorization** is a bit to long as a name for this category ... It does not really fit into the list if you have a look into the short other names like **Files** or **Multimedia** 😜 

@BernhardPosselt

**Comment by BernhardPosselt** [comment]
The shorthand for this category is auth. Authorization and authentication are not the same thing so I don't think we can group them together like this,

Examples:
* **Authentication**: Check if a user is logged in
* **Authorization**: Check if a user is allowed to do something

The category should include stuff like: 
* LDAP or AD backend
* Two factor auth
* OAuth
* File firewall
* ACLs
* etc

Personally I can't find a better and shorter category, but if someone can it's ofc better to keep it shorter. Since the category id is already in use the result should named in a way that you can easily connect it to its id, **auth**.

**Comment by BernhardPosselt** [comment]
BTW: if we settle on a better description, the relevant files to change are here:
* https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/fixtures/categories.json#L97
* https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/core/templates/translation/db_translations.txt#L1
