### ISSUE TITLE
add a user profile

### ISSUE THREAD

**Issue by adsworth** [nextcloud/appstore#39]
add a user profile with:
-list of apps and their releases. Allow deleting of apps and releases, but no editing. Updates should be done via the API.
- allow changing of password.

Anything else?

**Comment by BernhardPosselt** [comment]
Once tokens are in we want to regenerate tokens

You should also see a list of apps that you co-maintain and be able to delete those releases but not the apps themselves.

Maybe also allow changing display names since and email addresses

**Comment by janibonnevier** [comment]
IRC with @BernhardPosselt:

- Rename "Profile" to "Account" because it is a set of private settings pages (profiles are usually public).
- Username change on first page.
- This ticket is too big, so split it up into multiple issues, about 1 per feature/page.

Push incoming for #147 that applies the first two of above points to what @adsworth has already done. I suggest we finish in #147 the four pages/features that have been started there, and thereafter create one PR for each feature.

**Comment by BernhardPosselt** [comment]
Closing this in favor of #195
