### ISSUE TITLE
Add some basic statistics

### ISSUE THREAD

**Issue by sualko** [nextcloud/appstore#487]
It would be super helpful for developers to known how many people downloaded an app release and which nc version they use.

**Comment by juliushaertl** [comment]
Not sure if the app store can handle this with the current implementation, since all downloads will be made directly from the URL where the release is stored. But it would be nice to have some details from the survey_client app on what are the most installed apps and what server version the apps are used with. 

@schiessle @nickvergessen

**Comment by sualko** [comment]
Thanks for the quick response. Download counts are nice and in my case easily obtained from [githubs api](https://help.github.com/articles/getting-the-download-count-for-your-releases/), but as you said some more fine grained information would be nice. I will open an issue in the usage stat repo.
