### ISSUE TITLE
Require at least one URL for app entries

### ISSUE THREAD

**Issue by dragetd** [nextcloud/appstore#541]
[Enhancement]
Hello,

it would be nice, if the store would require for an application to be listed to have one URL attached as a resource at least. I believe that every app does have at least a repository or some sort of development page.

Good example: https://apps.nextcloud.com/apps/deck

I was hoping to find a changelog for the last update. NextCloud provides a link to the store, which is a dead end on this side. Auto-Including the changelog might be another idea, but for now, a link to their GitHub would be nice. And if the store would enforce such things.

**Comment by BernhardPosselt** [comment]
> it would be nice, if the store would require for an application to be listed to have one URL attached as a resource at least. I believe that every app does have at least a repository or some sort of development page.

The resources section wont be rendered now if no resource is available (needs a deployment). Some apps are so simple (e.g. https://apps.nextcloud.com/apps/lsd) that requiring a resource does not make sense, therefore optional.

Issue trackers are required and displayed down in the discussion section (Report problem, Request  feature).

> I was hoping to find a changelog for the last update. NextCloud provides a link to the store, which is a dead end on this side. 

I don't really know what you mean but we do not handle Nextcloud integration.

> Auto-Including the changelog might be another idea, but for now, a link to their GitHub would be nice. And if the store would enforce such things.

A changelog is not required but if one is present it will be used, see http://nextcloudappstore.readthedocs.io/en/latest/developer.html#changelog I don't think enforcing it is a good idea since we will break at least half of all uploads. Also not every release will have changes, e.g. version number increases to purely trigger database migrations. Contact the app maintainer to provide a proper changelog.

**Comment by juliushaertl** [comment]
@BernhardPosselt The deck app defines a repository in the appinfo.xml 

    <repository type="git">https://github.com/nextcloud/deck.git</repository>

Maybe that should also be linked in the "Resources" list.

>  Auto-Including the changelog might be another idea, but for now, a link to their GitHub would be nice. 

@dragetd As stated in https://github.com/nextcloud/deck/issues/389 we have changelogs that are also visible in the app store: https://apps.nextcloud.com/apps/deck/releases?platform=13#13
