### ISSUE TITLE
App details are not updated to the latest upload if only pre-releases or nightlies exist

### ISSUE THREAD

**Issue by PhieF** [nextcloud/appstore#581]
Hi, 

I've put a new app on the nextcloud app repo, with what seems to be a correct info.xml, but it doesn't take description categories and screenshot into account, 

see there

https://apps.nextcloud.com/apps/carnet

Any ideas why ? Thanks !

**Comment by BernhardPosselt** [comment]
Because there's no stable release. Pre-releases don't set any content to avoid overriding the current stable page.

See https://github.com/nextcloud/appstore/blob/master/nextcloudappstore/api/v1/release/importer.py#L268

Probably 

    if len(releases) == 0:

should be adjusted to filter out unstable releases so if no stable release is present, unstable releases will always update the current page.

**Comment by BernhardPosselt** [comment]
Do you think you can take on the issue and send a pull request?

**Comment by PhieF** [comment]
Oh eeerr yes why not but I don't have the project, I can do it if you want but I don't feel like I've fixed the bug... since you did :P 
(the main issue is that I have no ways to test it)

**Comment by BernhardPosselt** [comment]
See https://nextcloudappstore.readthedocs.io/en/latest/devinstall.html

Will probably take a few months until I have some spare time. Releasing a stable release should fix your issue so I don't think it's very dramatic.

**Comment by PhieF** [comment]
Thanks ! I've just posted a release

**Comment by skjnldsv** [comment]
Any news here? :grin:

**Comment by mario** [comment]
Suuuure ... the news is that there's no news until you bribe someone to do it @skjnldsv :P
