### ISSUE TITLE
App security 

### ISSUE THREAD

**Issue by 0e318236-1680-41a8-a989-3c9227637cdf** [nextcloud/appstore#606]
Is there security overview, or recomended practices when installing apps?

When I installed some apps, I dont think I had to grant any permissions.

Some of the apps seem to have a lot of features; Is there some way to see if app is behaving malicously? ie uploading files without user requests, or phoning home with analytics?

**Comment by 0e318236-1680-41a8-a989-3c9227637cdf** [comment]
Suppose I should just restrict access to ip when in cloud, but wonder if I need to secure within a closed office network.

**Comment by BernhardPosselt** [comment]
> When I installed some apps, I dont think I had to grant any permissions.

That is because Nextcloud apps have full access to Nextcloud and the directories/services that it can access. There is no sandboxing mechanism.

Android ships a complete Linux operating system with proper sandboxing, GNOME ships a separate runtime for Flatpak which uses Linux to sandbox operating system resources. This low level stuff is simply not available by default, even less so if you use PHP. 

You'd probably have to use containers and implement some sort of IPC and event system for apps to talk to each other: very complex to setup and design, slow and hard for home users to set up. Every app would ship its own PHP interpreter and database. The only other option would be to handle this stuff on interpreter level and then we'd ship our own PHP version. Either way webhosting would be impossible. 

> Some of the apps seem to have a lot of features; Is there some way to see if app is behaving  malicously? ie uploading files without user requests, or phoning home with analytics?

You are responsible for installing apps that you trust. There is no way to tell if an app does certain things without proper sandboxing and reading its source code. Even on Android it's complicated: does an app upload your contacts if you give it access to your contact list? You don't know unless you decompile the binaries and read the actual code. 

It is your responsibility to review it properly although I'd argue that it is impossible for mere mortals. We don't review community apps either because we are lacking the manpower and tools to review hundreds of apps and their library dependencies. Even if we had, good luck reviewing minified js files with lots of deps from node or dependencies from composer. 

The only thing that we offer is code signing which allows you to verify that an archive was uploaded by users with access to the certificate. That way even if the store was compromised an attacker wouldn't be able to ship you malicious updates for apps whose certificates he does not have access to.

If we are notified of bad behavior we will revoke all related certificates and remove the apps them from the store. Nextcloud also needs an update for the revoked certificate list. After this update, apps with revoked certificates won't be installable via the web interface.

> Is there security overview, or recomended practices when installing apps?

If you are risk averse you should install as few apps as possible and limit it to official Nextcloud apps.

**Comment by 0e318236-1680-41a8-a989-3c9227637cdf** [comment]
Thanks, I was a little wary about installing apps willy nilly. I trust official badges a little more (since Im assuming sources are provided) than third party, but will look into setting up a bit more secure env.
