### ISSUE TITLE
App Changelog fails to parse

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/appstore#630]
It is not clear that changlog information presented in the app store depends on a specific format of the CHANGELOG file. In case of the bookmarks app the changes wouldn't be picked up because the headings sported an extra `v` in front of the version number.

I propose to either 

a) document the specific format requirements
b) extend the parser to handle other formats (see https://github.com/nextcloud/appstore/blob/744859a5e40c7e0f49df98f8aeab1c451815ad01/nextcloudappstore/api/v1/release/parser.py#L323 )

Thanks.

**Comment by aszlig** [comment]
Note that the [documentation](https://nextcloudappstore.readthedocs.io/en/latest/developer.html#changelog) states quite clearly:

> Changelogs have to follow the [Keep a CHANGELOG](https://keepachangelog.com/en/1.0.0/) format

I think it might make more sense to make it possible to provide an out-of-band changelog in case the changelog doesn't comply with this, because relaxing the strictness of the parsing (even though I personally would still consider it pretty lax in the current state) would make the parsing more error-prone.

Of course, I doubt that (in this case) just allowing the `v` prefix would make the parsing significantly worse, but where do you draw the line?

**Comment by marcelklehr** [comment]
Oh, that's great! This is the first time I'm exposed to the docs for the app store. :astonished: 

I will refactor my changelog then.
