### ISSUE TITLE
[Request] Feature Memories App

### ISSUE THREAD

**Issue by meichthys** [nextcloud/appstore#942]
Could you please feature the [Memories App](https://apps.nextcloud.com/apps/memories)?
Some reasons for this were provided here: https://github.com/nextcloud/photos/issues/1509 , but I think the request better fits this repository.

Quoting the request from the photos repository, here are the reasons we think the Memories app is a good candidate for being featured:

> I have used nextcloud on and off for a long time and photos continue to be my primary reason for looking else where. I don't mean to be disrespectful, but it can be acknowledged that the default photos app is not usable if you have a lot of photos. There has been a lot of discussion about this on this on reddit, but I am not sure the devs use reddit, so posting this here. From a google search,
> 
> https://www.reddit.com/r/NextCloud/comments/n5jaqz/nextcloud_photos_still_useless/
> https://www.reddit.com/r/NextCloud/comments/k6qmt8/alternative_to_nextclouds_photo_gallery/
> https://www.reddit.com/r/NextCloud/comments/jue32m/viewing_nextcloud_photos_without_losing_ones_mind/
> https://www.reddit.com/r/NextCloud/comments/qr9q4d/nextcloud_app_for_better_photo_sharing/
> 
> I only very recently came to know about this app called memories from another reddit post https://www.reddit.com/r/selfhosted/comments/z245mo/loading_40k_images_in_one_view_with_memories/. I have been using it for a few days and it is very smooth and usable for thousands of photos, and as good as even dedicated photo apps like photoprism. But unfortunately I never found it before because there is no way unless you search for it or look through all apps in the app store. Link to the app: https://github.com/pulsejet/memories
> 
> The creator of memories has mentioned there are no plans to make the app official https://github.com/pulsejet/memories/issues/183, but would it be possible to at least add a link somewhere to let users know that something like this exists? Again I don't mean to be disrespectful, but I think the lack of a good photos app for large libraries hurts nextcloud, especially when so many of us run a server especially for photo backup. And the only solution you see for nextcloud when you first install nextcloud is the default photos app.

**Comment by ChildLearningClub** [comment]
I could not agree more! I only randomly came across the memories app when trying to figure out how to transcode shared videos. For reference I think the only other open source tool that does this well is PiGallery2.  The Memories app is phenomenal but is kind of left obscure and hidden among all the other apps. @pulsejet has created a valuable asset for Nextcloud it would be nice to see it at the very least featured. If I worked at Nextcloud that [UCLA computer graduate](https://varunpp2.medium.com/nextcloud-memories-putting-thousands-of-photos-on-the-world-map-1376cf4105a0) would already have a job! If I didn't have space I would make it.

**Comment by joshtrichards** [comment]
I suspect looping in someone like @DaphneMuller to discuss this situation (and maybe brainstorm some ways of collaborating) would make some sense here. 

This isn't a technical matter with the app store though. :-)

**Comment by luxzg** [comment]
Memories app is SO GOOD that it should earn a place in the official post-install setup, probably as a dedicated additional screen in that "slide show" that appears on first login. ( https://github.com/nextcloud/firstrunwizard )

In the documentation there's already 3rd party apps (Collabora?), and I think at very least Memories deserves a link here:

https://docs.nextcloud.com/server/latest/admin_manual/installation/apps_supported.html

It should also be in the list of featured apps on the apps website here:

https://apps.nextcloud.com/featured

I'd be as blunt to even say it could be installed but not enabled, or somehow promoted in the apps settings inside Nextcloud itself.

I actually kept both Photos and Memories on my NC server, but I find myself using Memories way more (almost exclusively lately).

Project itself is well maintained, up to date, and certainly mote responsive to the user requests. And who knows, maybe giving it a little spotlight would bring it some more devs and PRs so that pulsejet has some help with it.

Anyway, idea has my both thumbs up 👍👍 as this is the least I could do to somehow repay to pulsejet for his tireless efforts. Cheers!
