### ISSUE TITLE
Change author information of https://apps.nextcloud.com/apps/keeweb

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/appstore#986]
[Keeweb](https://apps.nextcloud.com/apps/keeweb) is maintained by Arno Welzel and Jonne Haß together and the app information also contains "Jonne Haß, Arno Welzel" as author information, see https://github.com/jhass/nextcloud-keeweb/blob/v0.6.12/keeweb/appinfo/info.xml

I already asked @jhass in the past, if it is possible to change the information in the nextcloud app store to reflect this, but he did not know how to to this and it seems that this information is not updated based on the information in `info.xml`.

So how to change the author information?

**Comment by christian-wolf-eks** [comment]
@jhass please state your clear consent with the update of the information in the app store by commenting on this issue here.

Once this consent is here in written form, an admin can be pinged in order to set the gears into action. Eventually, the admin might ask for further authentication but you will see (and eventually get instructions then).

**Comment by jhass** [comment]
I fully consent with the request.

**Comment by christianlupus** [comment]
@jhass thanks for your clear consent with the update of the information in the app store by commenting on this issue here.

Once this consent is here in written form, an admin can be pinged in order to set the gears into action. Eventually, the admin might ask for further authentication but you will see (and eventually get instructions then).

Could you please forward this (or ping the appropriate person), @blizzz? Thanks a lot!
