### ISSUE TITLE
IP block of my VPS

### ISSUE THREAD

**Issue by cab404** [nextcloud/appstore#987]
## Details

I have problems using my Scaleway machine as a Nextcloud server. 
It can't run app updates — all requests get rejected.
Can you please unblock my IP?

`51.15.83.8`

**Comment by joshtrichards** [comment]
What indication do you have the connections are rejected? Is there a precise error message?

Are you able to manually check connectivity to `apps.nextcloud.com` via `ping` and `curl` from your host?

**Comment by bigcat88** [comment]
@cab404 is this is still actual?

**Comment by cab404** [comment]
Sorry, I will check in rn — server was down for quite a while.

**Comment by joshtrichards** [comment]
This isn't the appstore. Apparently your server isn't able to access GitHub for some reason.

I assume something similar happens if you try something like `wget https://github.com/nextcloud-releases/calendar/releases/download/v4.4.4/calendar-v4.4.4.tar.gz` from the command line of your server?

Are you sure your app server is functioning *outbound* connectivity to the Internet?

**Comment by cab404** [comment]
> Are you sure your app server is functioning _outbound_ connectivity to the Internet?

Yeah, I think I've messed up my routes. For a second it looked like Nextcloud is the only thing that doesn't work — and since I am proxying traffic through Caddy and Wireguard connection from it to server did work, that made me think that it's just Nextcloud updates. I thought that I've checked other websites, but I guess I fake remembered it)

Sorry for the trouble and thank you!
